version: "3.7"
services:
  apigateway:
    image: apigateway
    container_name: apigateway
    ports:
      - "5171:80"
    build:
      context: .
      dockerfile: Dockerfile.WebApiGateway
    networks:
      - real
  api1:
    image: app1
    container_name: app1
    ports:
      - "5172:80" 
    build:
      context: .
      dockerfile: Dockerfile.WebApi1
    networks:
      - real
  app2:
    image: app2
    container_name: app2
    ports:
      - "5173:80"
    build:
      context: .
      dockerfile: Dockerfile.WebApi2
    networks:
      - real
networks:
  real: